apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: first-node
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "europe"

---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: second-node
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "africa"
